### ISSUE TITLE
Can I sync two VCV on different computers without Ableton?

### ISSUE THREAD

**Issue by MockbaTheBorg** [stellare-modular/vcv-link#8]
On the vcv-link readme it is said that we can also link two VCV instances running on different computers that are on the same LAN or WLAN.
It has not become immediately clear to me how this can be achieved.
I have created two patches with link on them, but, other than their clock being the same, it is not clear how can I make one synced to the other's tempo, or beat, or at all.

Maybe I am missing a point here, forgive-me if that's the case. Thanks!

**Comment by sanderbaan** [comment]
Hi, in this setup the tempo will always be 120 BPM because we have no tempo control in the link module itself so its set to its default tempo of 120 BPM, to work around this you could launch Ableton on one of the computers or any other link host and change the tempo you will then see that the tempo follows on both VCV instances. The gate outputs give the tempo sync the Reset output the phase sync.

**Comment by MockbaTheBorg** [comment]
Oh ok ... I see now what I was missing.
It is that I am trying to synchronize two VCV without needing to install Ableton.
I am trying to write a master/slave clock using UDP then. Maybe it will work.
It would be cool if you could write a Link-Master ... :) .. not sure how complicated that would be, but it could eliminate Ableton altogether.

Thanks a lot! You can close this one.

**Comment by jamshark70** [comment]
FWIW: Link does not require Ableton Live. You can use *any* other software that supports Link: a metronome mobile app would do it.

Or free, open-source apps like SuperCollider (which, in recent versions, includes Link support):

```
l = LinkClock.new(120/60);

l.tempo = (your new tempo) / 60;
```
